   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  11/01/16            */
   /*                                                     */
   /*             CLASS EXAMINATION HEADER FILE           */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: The CL_DescribeClass macros were incorrectly      */
/*            defined. DR0862                                */
/*                                                           */
/*            Added allowed-classes slot facet.              */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Added Env_SlotDefaultP function.                */
/*                                                           */
/*            Borland C (IBM_TBC) and Metrowerks CodeWarrior */
/*            (MAC_MCW, IBM_MCW) are no longer supported.    */
/*                                                           */
/*            Used CL_gensprintf and CL_genstrcat instead of       */
/*            sprintf and strcat.                            */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*            ALLOW_ENVIRONMENT_GLOBALS no longer supported. */
/*                                                           */
/*            UDF redesign.                                  */
/*                                                           */
/*************************************************************/

#ifndef _H_classexm

#pragma once

#define _H_classexm

#include "entities.h"
#include "object.h"

#if DEBUGGING_FUNCTIONS

   void                           CL_BrowseClassesCommand(Environment *,UDFContext *,UDFValue *);
   void                           CL_BrowseClasses(Defclass *,const char *);
   void                           Describe_ClassCommand(Environment *,UDFContext *,UDFValue *);
   void                           CL_DescribeClass(Defclass *,const char *);

#endif /* DEBUGGING_FUNCTIONS */

   const char                    *CL_GetCreateAccessorString(SlotDescriptor *);
   void                           Get_DefclassModuleCommand(Environment *,UDFContext *,UDFValue *);
   void                           CL_SuperclassPCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SuperclassP(Defclass *,Defclass *);
   void                           CL_SubclassPCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SubclassP(Defclass *,Defclass *);
   void                           CL_SlotExistPCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SlotExistP(Defclass *,const char *,bool);
   void                           CL_MessageHandlerExistPCommand(Environment *,UDFContext *,UDFValue *);
   void                           CL_SlotWritablePCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SlotWritableP(Defclass *,const char *);
   void                           CL_SlotInitablePCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SlotInitableP(Defclass *,const char *);
   void                           CL_SlotPublicPCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SlotPublicP(Defclass *,const char *);
   void                           CL_SlotDirectAccessPCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SlotDirectAccessP(Defclass *,const char *);
   void                           CL_SlotDefaultValueCommand(Environment *,UDFContext *,UDFValue *);
   bool                           CL_SlotDefaultValue(Defclass *,const char *,CLIPSValue *);
   void                           CL_ClassExistPCommand(Environment *,UDFContext *,UDFValue *);
   int                            CL_SlotDefaultP(Environment *,Defclass *,const char *);

#endif /* _H_classexm */
