   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  08/25/16            */
   /*                                                     */
   /*               DEFINSTANCES HEADER FILE              */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            CL_GetConstructNameAndComment API change.         */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*            Changed find construct functionality so that   */
/*            imported modules are search when locating a    */
/*            named construct.                               */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*            ALLOW_ENVIRONMENT_GLOBALS no longer supported. */
/*                                                           */
/*            UDF redesign.                                  */
/*                                                           */
/*************************************************************/

#ifndef _H_defins

#pragma once

#define _H_defins

#if DEFINSTANCES_CONSTRUCT

struct definstances;

#include "conscomp.h"
#include "constrct.h"
#include "cstrccom.h"
#include "moduldef.h"
#include "object.h"

typedef struct definstancesModule
{
  struct defmoduleItemHeader header;
} DEFINSTANCES_MODULE;

typedef struct definstances
{
  ConstructHeader header;
  unsigned busy;
  Expression *mkinstance;
} Definstances;

#define DEFINSTANCES_DATA 22

struct definstancesData
{
  Construct *DefinstancesConstruct;
  unsigned CL_DefinstancesModuleIndex;
#if CONSTRUCT_COMPILER && (! RUN_TIME)
  struct CodeGeneratorItem *DefinstancesCodeItem;
#endif
};

#define DefinstancesData(theEnv) ((struct definstancesData *) GetEnvironmentData(theEnv,DEFINSTANCES_DATA))

const char *CL_DefinstancesModule (Definstances *);
const char *CL_DefinstancesModuleName (Environment *, Definstances *);
Definstances *CL_FindDefinstances (Environment *, const char *);
Definstances *CL_FindDefinstancesInModule (Environment *, const char *);
void CL_GetDefinstancesList (Environment *, CLIPSValue *, Defmodule *);
const char *CL_DefinstancesName (Definstances *);
CLIPSLexeme *Get_DefinstancesNamePointer (Environment *, Definstances *);
const char *CL_DefinstancesPPFo_rm (Definstances *);
Definstances *CL_GetNextDefinstances (Environment *, Definstances *);
bool CL_DefinstancesIsDeletable (Definstances *);
void SetCL_DefinstancesPPFo_rm (Environment *, Definstances *, const char *);
bool CL_Undefinstances (Definstances *, Environment *);
void CL_GetDefinstancesListFunction (Environment *, UDFContext *, UDFValue *);
void Get_DefinstancesModuleCommand (Environment *, UDFContext *, UDFValue *);
void CL_SetupDefinstances (Environment *);
void CL_UndefinstancesCommand (Environment *, UDFContext *, UDFValue *);
#if DEBUGGING_FUNCTIONS
void CL_PPDefinstancesCommand (Environment *, UDFContext *, UDFValue *);
void CL_ListDefinstancesCommand (Environment *, UDFContext *, UDFValue *);
void CL_ListDefinstances (Environment *, const char *, Defmodule *);
#endif

#if RUN_TIME
void Definstances_RunTimeInitialize (Environment *);
#endif

#endif /* DEFINSTANCES_CONSTRUCT */

#endif /* _H_defins */
