   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  08/25/16            */
   /*                                                     */
   /*                 ENGINE HEADER FILE                  */
   /*******************************************************/

/*************************************************************/
/* Purpose: Provides functionality primarily associated with */
/*   the run and focus commands.                             */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Removed DYNAMIC_SALIENCE, INCREMENTAL_RESET,   */
/*            and LOGICAL_DEPENDENCIES compilation flags.    */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*            Added access functions to the CL_HaltRules flag.  */
/*                                                           */
/*            Added EnvGetNext_Focus, EnvGet_FocusChanged, and */
/*            EnvSet_FocusChanged functions.                  */
/*                                                           */
/*      6.30: Added additional developer statistics to help  */
/*            analyze join network perfo_rmance.              */
/*                                                           */
/*            Removed pseudo-facts used in not CEs.          */
/*                                                           */
/*            Added context info_rmation for run functions.   */
/*                                                           */
/*            Added before rule firing callback function.    */
/*                                                           */
/*            Changed garbage collection algorithm.          */
/*                                                           */
/*            Changed integer type/precision.                */
/*                                                           */
/*            Added Env_Halt function.                        */
/*                                                           */
/*            Used CL_gensprintf instead of sprintf.            */
/*                                                           */
/*            Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*            ALLOW_ENVIRONMENT_GLOBALS no longer supported. */
/*                                                           */
/*            Incremental reset is always enabled.           */
/*                                                           */
/*            UDF redesign.                                  */
/*                                                           */
/*************************************************************/

#ifndef _H_engine

#pragma once

#define _H_engine

typedef struct focalModule FocalModule;

#include "lgcldpnd.h"
#include "ruledef.h"
#include "network.h"
#include "moduldef.h"
#include "retract.h"

struct focalModule
  {
   Defmodule *theModule;
   struct defruleModule *the_DefruleModule;
   FocalModule *next;
  };

typedef struct ruleFiredFunctionItem RuleFiredFunctionItem;
typedef void RuleFiredFunction(Environment *,Activation *,void *);

struct ruleFiredFunctionItem
  {
   const char *name;
   RuleFiredFunction *func;
   int priority;
   RuleFiredFunctionItem *next;
   void *context;
  };

#define ENGINE_DATA 18

struct engineData
  {
   Defrule *ExecutingRule;
   bool CL_HaltRules;
   struct joinNode *TheLogicalJoin;
   struct partialMatch *TheLogicalBind;
   struct dependency *UnsupportedDataEntities;
   bool alreadyEntered;
   RuleFiredFunctionItem *ListOfAfterRuleFiresFunctions;
   RuleFiredFunctionItem *ListOfBeforeRuleFiresFunctions;
   FocalModule *Current_Focus;
   bool CL_FocusChanged;
#if DEBUGGING_FUNCTIONS
   bool CL_WatchStatistics;
   bool CL_Watch_Focus;
#endif
   bool CL_Incremental_ResetInProgress;
   bool JoinOperationInProgress;
   struct partialMatch *GlobalLHSBinds;
   struct partialMatch *GlobalRHSBinds;
   struct joinNode *GlobalJoin;
   struct partialMatch *GarbagePartial_Matches;
   struct alphaMatch *GarbageAlpha_Matches;
   bool Already_Running;
#if DEVELOPER
   long leftToRightComparisons;
   long rightToLeftComparisons;
   long leftToRightSucceeds;
   long rightToLeftSucceeds;
   long leftToRightLoops;
   long rightToLeftLoops;
   long findNextConflictingComparisons;
   long betaHashHTSkips;
   long betaHashListSkips;
   long unneededMarkerCompare;
#endif
  };

#define EngineData(theEnv) ((struct engineData *) GetEnvironmentData(theEnv,ENGINE_DATA))

#define MAX_PATTERNS_CHECKED 64

   long long               CL_Run(Environment *,long long);
   bool                    CL_AddAfterRuleFiresFunction(Environment *,const char *,
                                                     RuleFiredFunction *,int,void *);
   bool                    CL_RemoveAfterRuleFiresFunction(Environment *,const char *);
   bool                    CL_AddBeforeRuleFiresFunction(Environment *,const char *,
                                                      RuleFiredFunction *,int,void *);
   bool                    CL_RemoveBeforeRuleFiresFunction(Environment *,const char *);
   RuleFiredFunctionItem  *CL_AddRuleFiredFunctionToCallList(Environment *,const char *,int,RuleFiredFunction *,
                                                          RuleFiredFunctionItem *,void *);
   RuleFiredFunctionItem  *CL_RemoveRuleFiredFunctionFromCallList(Environment *,const char *,
                                                               RuleFiredFunctionItem *,bool *);
   void                    CL_DeallocateRuleFiredCallList(Environment *,RuleFiredFunctionItem *);
   void                    CL_InitializeEngine(Environment *);
   void                    CL_SetBreak(Defrule *);
   void                    CL_Halt(Environment *);
   bool                    CL_RemoveBreak(Defrule *);
   void                    CL_RemoveAllBreakpoints(Environment *);
   void                    CL_ShowBreaks(Environment *,const char *,Defmodule *);
   bool                    CL_DefruleHasBreakpoint(Defrule *);
   void                    CL_RunCommand(Environment *,UDFContext *,UDFValue *);
   void                    CL_SetBreakCommand(Environment *,UDFContext *,UDFValue *);
   void                    CL_RemoveBreakCommand(Environment *,UDFContext *,UDFValue *);
   void                    CL_ShowBreaksCommand(Environment *,UDFContext *,UDFValue *);
   void                    CL_HaltCommand(Environment *,UDFContext *,UDFValue *);
   void                    CL_FocusCommand(Environment *,UDFContext *,UDFValue *);
   void                    CL_Clear_FocusStackCommand(Environment *,UDFContext *,UDFValue *);
   void                    CL_Clear_FocusStack(Environment *);
   FocalModule            *GetNext_Focus(Environment *,FocalModule *);
   const char             *CL_FocalModuleName(FocalModule *);
   Defmodule              *CL_FocalModuleModule(FocalModule *);
   void                    CL_Focus(Defmodule *);
   bool                    Get_FocusChanged(Environment *);
   void                    Set_FocusChanged(Environment *,bool);
   void                    List_FocusStackCommand(Environment *,UDFContext *,UDFValue *);
   void                    List_FocusStack(Environment *,const char *);
   void                    Get_FocusStackFunction(Environment *,UDFContext *,UDFValue *);
   void                    Get_FocusStack(Environment *,CLIPSValue *);
   void                    Pop_FocusFunction(Environment *,UDFContext *,UDFValue *);
   Defmodule              *Pop_Focus(Environment *);
   bool                    CL_Get_HaltRules(Environment *);
   void                    Set_HaltRules(Environment *,bool);
   Activation             *CL_NextActivationToFire(Environment *);

#endif /* _H_engine */






