   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  08/25/16            */
   /*                                                     */
   /*              FACT FUNCTIONS HEADER FILE             */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Added ppfact function.                         */
/*                                                           */
/*      6.30: Support for long long integers.                */
/*                                                           */
/*            Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*            UDF redesign.                                  */
/*                                                           */
/*************************************************************/

#ifndef _H_factfun

#pragma once

#define _H_factfun

#include "factmngr.h"

   void                           CL_FactFunctionDefinitions(Environment *);
   void                           CL_FactRelationFunction(Environment *,UDFContext *,UDFValue *);
   CLIPSLexeme                   *CL_FactRelation(Fact *);
   Deftemplate                   *CL_FactDeftemplate(Fact *);
   void                           CL_FactExistpFunction(Environment *,UDFContext *,UDFValue *);
   bool                           CL_FactExistp(Fact *);
   void                           CL_FactSlotValueFunction(Environment *,UDFContext *,UDFValue *);
   void                           CL_FactSlotValue(Environment *,Fact *,const char *,CLIPSValue *);
   void                           CL_FactSlotNamesFunction(Environment *,UDFContext *,UDFValue *);
   void                           CL_FactSlotNames(Fact *,CLIPSValue *);
   void                           CL_GetFactListFunction(Environment *,UDFContext *,UDFValue *);
   void                           CL_GetFactList(Environment *,CLIPSValue *,Defmodule *);
   void                           CL_PPFactFunction(Environment *,UDFContext *,UDFValue *);
   void                           CL_PPFact(Fact *,const char *,bool);
   Fact                          *CL_GetFactAddressOrIndexArgument(UDFContext *,bool);

#endif /* _H_factfun */

